import { Client, Account } from 'node-appwrite';

/**
 * Verify an Appwrite JWT Token generated by the frontend Web SDK.
 * Returns the decoded token payload or null if invalid
 * Accepts either:
 *   - Full auth header: "Bearer <token>"
 *   - Just the token: "<token>"
 */
export async function verifyIdToken(tokenOrHeader: string | null): Promise<{
    uid: string;
    email: string | undefined;
} | null> {
    if (!tokenOrHeader) {
        return null;
    }

    // Handle both formats: "Bearer <token>" or just "<token>"
    let token: string;
    if (tokenOrHeader.startsWith('Bearer ')) {
        token = tokenOrHeader.split('Bearer ')[1];
    } else {
        token = tokenOrHeader;
    }

    try {
        const client = new Client()
            .setEndpoint(process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT || 'https://cloud.appwrite.io/v1')
            .setProject(process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!)
            .setJWT(token);

        // Fetch the user strictly using their ephemeral JWT
        const account = new Account(client);
        const user = await account.get();

        return {
            uid: user.$id,
            email: user.email,
        };
    } catch (error) {
        console.error('[Auth] Token verification failed:', error);
        return null;
    }
}

/**
 * Helper to extract and verify auth from request
 * Returns user info or null if not authenticated
 */
export async function getAuthFromRequest(request: Request): Promise<{
    userId: string;
    userEmail: string;
} | null> {
    const authHeader = request.headers.get('Authorization');
    const verified = await verifyIdToken(authHeader);

    if (!verified) {
        return null;
    }

    return {
        userId: verified.uid,
        userEmail: verified.email || '',
    };
}
